ccflags-y += -I$(srctree)/techpack/bt/include
ccflags-y += -I$(srctree)/techpack/bt/btfmcodec/include
btfmcodec-objs := btfm_codec.o btfm_codec_hw_interface.o btfm_codec_interface.o btfm_codec_btadv_interface.o
obj-$(CONFIG_BTFM_CODEC) += btfmcodec.o
