# SPDX-License-Identifier: GPL-2.0-only

include $(srctree)/techpack/mm/config/kalamammdrivers.conf
LINUXINCLUDE += -include $(srctree)/techpack/mm/config/kalamammdriversconf.h
ccflags-y += -I$(srctree)/techpack/mm/msm_ext_display/include

obj-m += msm_ext_display.o

msm_ext_display-y := src/msm_ext_display.o

EXTRA_CFLAGS += -Wformat-extra-args -Wstrict-prototypes -Wformat-insufficient-args \
		-Wformat-invalid-specifier -Wformat-zero-length -Wnonnull
