
include $(srctree)/techpack/mmrm/config/waipiommrm.conf
LINUXINCLUDE += -include $(srctree)/techpack/mmrm/config/waipiommrmconf.h

ifneq ($(CONFIG_ARCH_QTI_VM), y)

obj-m += driver/
# obj-m += test/

ifeq ($(CONFIG_MSM_MMRM_VM),y)
LINUXINCLUDE += -I$(srctree)/techpack/mmrm/vm/common/inc/
obj-m += vm/be/
endif

else

LINUXINCLUDE += -I$(srctree)/techpack/mmrm/vm/common/inc/

obj-m += vm/fe/
# obj-y += vm/fe/vm_test/

endif
